# Generated by Django 3.2.9 on 2021-11-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
