# Generated by Django 3.2.9 on 2021-11-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_alter_reply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='videoId',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
