# Generated by Django 3.2.9 on 2021-11-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_reply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment_Id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='youtube.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(max_length=300),
        ),
    ]
