# Generated by Django 3.2.9 on 2021-11-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_auto_20211109_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment_Id',
            new_name='comment',
        ),
    ]
