# Generated by Django 3.2.9 on 2021-11-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_auto_20211109_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
